on: 
  schedule:
  - cron: '0 */6 * * *'
name: Daily publish on Netlify
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
          node-version: '12.x'
    - run: | 
        yarn install --frozen-lockfile
        yarn build
        yarn export

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
