on: push
#  schedule:
#  - cron: '0 7 * * *'
name: Daily publish on Netlify
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
          node-version: '11.x'
          
    - name: Yarn install
    - run: yarn install --frozen-lockfile
      env:
        CI: true
    - run: ls -lat
    - uses: netlify/actions/cli@master
      with:
        args: build
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
